bitrise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,14 +1,126 @@
+---
 format_version: 1.2.0
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
-
+app:
+  envs:
+  - DOCKERHUB_IMG_ID: bitriseio/website-docker-base-env
+  # define in .bitrise.secrets.yml
+  - DOCKER_LOGIN_EMAIL: $DOCKER_LOGIN_EMAIL
+  - DOCKER_LOGIN_USER: $DOCKER_LOGIN_USER
+  - DOCKER_LOGIN_PASS: $DOCKER_LOGIN_PASS
+  # on CI
+  - SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
+  - SLACK_CHANNEL: $SLACK_CHANNEL
 workflows:
-  test:
+  rebuild:
     steps:
-    - script:
-        title: Docker rebuild
+    - script@1.1.0:
+        title: docker infos & images
         inputs:
-        - content: |-
+        - content: |
             #!/bin/bash
             set -ex
 
-            docker build --no-cache --pull .
+            docker images
+            df -kh ./
+            docker info
+    - script@1.1.0:
+        title: docker build
+        inputs:
+        - content: |
+            #!/bin/bash
+            set -ex
+
+            docker build --pull --no-cache -t "${DOCKERHUB_IMG_ID}:latest" .
+
+            docker images
+
+  _generate_image_deploy_tag:
+    steps:
+    - script:
+        inputs:
+        - content: |
+            #!/bin/bash
+            set -ex
+            if [ -z "$DOCKER_IMAGE_DEPLOY_TAG" ] ; then
+              echo " (i) DOCKER_IMAGE_DEPLOY_TAG not defined, generating one"
+              envman add --key 'DOCKER_IMAGE_DEPLOY_TAG' --value "$(date +%Y_%m_%d-%H_%M)"
+            fi
+
+  deploy:
+    before_run:
+    - rebuild
+    - _generate_image_deploy_tag
+    steps:
+    - slack@2.1.0:
+        run_if: .IsCI
+        inputs:
+        - webhook_url: $SLACK_WEBHOOK_URL
+        - channel: $SLACK_CHANNEL
+        - from_username: "$BITRISE_APP_TITLE - OK"
+        - from_username_on_error: "$BITRISE_APP_TITLE - ERROR"
+        - message: |
+            Started:
+
+            - Build URL: $BITRISE_BUILD_URL
+            - Build Number: $BITRISE_BUILD_NUMBER
+            - Image tag: $DOCKER_IMAGE_DEPLOY_TAG
+    - script@1.1.0:
+        title: docker login
+        inputs:
+        - content: |
+            #!/bin/bash
+            set -e
+            echo "=> Docker login..."
+            docker login -e "${DOCKER_LOGIN_EMAIL}" -u "${DOCKER_LOGIN_USER}" -p "${DOCKER_LOGIN_PASS}"
+    - script@1.1.0:
+        title: docker push
+        inputs:
+        - content: |
+            #!/bin/bash
+
+            function docker_push_with_retry {
+              local push_id="$1"
+              echo " => Pushing: ${push_id} ..."
+              docker push "${push_id}"
+              if [ $? -ne 0 ] ; then
+                echo " (!) WARNING: First push attempt failed - retry..."
+                sleep 10
+                docker push "${push_id}"
+                if [ $? -ne 0 ] ; then
+                  echo " [!] ERROR: Second push attempt failed"
+                  exit 1
+                fi
+              fi
+              echo " => Pushing - OK"
+            }
+
+            if [ -z "${DOCKER_IMAGE_DEPLOY_TAG}" ] ; then
+              echo " [!] No DOCKER_IMAGE_DEPLOY_TAG specified!"
+              exit 1
+            fi
+
+            echo " => Tagging: ${DOCKER_IMAGE_DEPLOY_TAG} ..."
+            docker tag -f "${DOCKERHUB_IMG_ID}:latest" "${DOCKERHUB_IMG_ID}:${DOCKER_IMAGE_DEPLOY_TAG}"
+            if [ $? -ne 0 ] ; then
+              echo " [!] ERROR: failed to tag the image"
+              exit 1
+            fi
+            docker_push_with_retry "${DOCKERHUB_IMG_ID}:${DOCKER_IMAGE_DEPLOY_TAG}"
+            docker_push_with_retry "${DOCKERHUB_IMG_ID}:latest"
+    - slack@2.1.0:
+        run_if: .IsCI
+        inputs:
+        - webhook_url: $SLACK_WEBHOOK_URL
+        - channel: $SLACK_CHANNEL
+        - from_username: "$BITRISE_APP_TITLE - OK"
+        - from_username_on_error: "$BITRISE_APP_TITLE - ERROR"
+        - message: |
+            Finished:
+
+            - Branch: *$BITRISE_GIT_BRANCH*
+            - Tag: $BITRISE_GIT_TAG
+            - Image tag: $DOCKER_IMAGE_DEPLOY_TAG
+            - Build URL: $BITRISE_BUILD_URL
+            - Build Number: $BITRISE_BUILD_NUMBER
+            - Build Message: $BITRISE_GIT_MESSAGE
